/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni_JNIUtil */

#ifndef _Included_com_example_hellojni_JNIUtil
#define _Included_com_example_hellojni_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni_JNIUtil
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_example_hellojni_JNIUtil_sayHello(JNIEnv *, jobject);

JNIEXPORT jint JNICALL
Java_com_example_hellojni_JNIUtil_sum(JNIEnv *env, jobject instance, jint x, jint y);

JNIEXPORT jstring JNICALL
Java_com_example_hellojni_JNIUtil_addstr(JNIEnv *env, jobject instance, jstring str_);

JNIEXPORT jintArray JNICALL
Java_com_example_hellojni_JNIUtil_increaseArrayEles(JNIEnv *env, jobject instance,
                                                                         jintArray intArray_);
JNIEXPORT jint JNICALL
Java_com_example_hellojni_JNIUtil_checkPwd(JNIEnv *env, jobject instance, jstring pwd_);

JNIEXPORT void JNICALL
Java_com_example_hellojni_JNIUtil_getBitmapInfo(JNIEnv *env,jobject instance,jobject bitmap);

JNIEXPORT void JNICALL
Java_com_example_hellojni_JNIUtil_arraySort(JNIEnv *env,jobject instance,jintArray array);

#ifdef __cplusplus
}
#endif
#endif
